name: JumpBoost
version: '${project.version}'
main: me.jaden.jumpboost.JumpBoost
api-version: 1.19

commands:
  jump:
    description: Permission to use the jump command
    usage: /jump menu
    permission: jumpboost.boost